Traceback (most recent call last):
  File "/Users/doya/anaconda3/envs/jbook/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/doya/anaconda3/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/doya/anaconda3/envs/jbook/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/doya/anaconda3/envs/jbook/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/doya/anaconda3/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/doya/anaconda3/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/doya/anaconda3/envs/jbook/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
y0 = np.array([0, 0])
t = np.arange(0, 100, 0.1)
y = odeint(fhn, y0, t, args=(0.5,))
plt.plot(t, y, '.-')  # trajectory
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mRuntimeError[0m                              Traceback (most recent call last)
Cell [0;32mIn[7], line 3[0m
[1;32m      1[0m y0 [38;5;241m=[39m np[38;5;241m.[39marray([[38;5;241m0[39m, [38;5;241m0[39m])
[1;32m      2[0m t [38;5;241m=[39m np[38;5;241m.[39marange([38;5;241m0[39m, [38;5;241m100[39m, [38;5;241m0.1[39m)
[0;32m----> 3[0m y [38;5;241m=[39m [43modeint[49m[43m([49m[43mfhn[49m[43m,[49m[43m [49m[43my0[49m[43m,[49m[43m [49m[43mt[49m[43m,[49m[43m [49m[43margs[49m[38;5;241;43m=[39;49m[43m([49m[38;5;241;43m0.5[39;49m[43m,[49m[43m)[49m[43m)[49m
[1;32m      4[0m plt[38;5;241m.[39mplot(t, y, [38;5;124m'[39m[38;5;124m.-[39m[38;5;124m'[39m)  [38;5;66;03m# trajectory[39;00m

File [0;32m~/anaconda3/envs/jbook/lib/python3.11/site-packages/scipy/integrate/_odepack_py.py:242[0m, in [0;36modeint[0;34m(func, y0, t, args, Dfun, col_deriv, full_output, ml, mu, rtol, atol, tcrit, h0, hmax, hmin, ixpr, mxstep, mxhnil, mxordn, mxords, printmessg, tfirst)[0m
[1;32m    240[0m t [38;5;241m=[39m copy(t)
[1;32m    241[0m y0 [38;5;241m=[39m copy(y0)
[0;32m--> 242[0m output [38;5;241m=[39m [43m_odepack[49m[38;5;241;43m.[39;49m[43modeint[49m[43m([49m[43mfunc[49m[43m,[49m[43m [49m[43my0[49m[43m,[49m[43m [49m[43mt[49m[43m,[49m[43m [49m[43margs[49m[43m,[49m[43m [49m[43mDfun[49m[43m,[49m[43m [49m[43mcol_deriv[49m[43m,[49m[43m [49m[43mml[49m[43m,[49m[43m [49m[43mmu[49m[43m,[49m
[1;32m    243[0m [43m                         [49m[43mfull_output[49m[43m,[49m[43m [49m[43mrtol[49m[43m,[49m[43m [49m[43matol[49m[43m,[49m[43m [49m[43mtcrit[49m[43m,[49m[43m [49m[43mh0[49m[43m,[49m[43m [49m[43mhmax[49m[43m,[49m[43m [49m[43mhmin[49m[43m,[49m
[1;32m    244[0m [43m                         [49m[43mixpr[49m[43m,[49m[43m [49m[43mmxstep[49m[43m,[49m[43m [49m[43mmxhnil[49m[43m,[49m[43m [49m[43mmxordn[49m[43m,[49m[43m [49m[43mmxords[49m[43m,[49m
[1;32m    245[0m [43m                         [49m[38;5;28;43mint[39;49m[43m([49m[38;5;28;43mbool[39;49m[43m([49m[43mtfirst[49m[43m)[49m[43m)[49m[43m)[49m
[1;32m    246[0m [38;5;28;01mif[39;00m output[[38;5;241m-[39m[38;5;241m1[39m] [38;5;241m<[39m [38;5;241m0[39m:
[1;32m    247[0m     warning_msg [38;5;241m=[39m _msgs[output[[38;5;241m-[39m[38;5;241m1[39m]] [38;5;241m+[39m [38;5;124m"[39m[38;5;124m Run with full_output = 1 to get quantitative information.[39m[38;5;124m"[39m

[0;31mRuntimeError[0m: The size of the array returned by func (1) does not match the size of y0 (2).

